---
title: "US Economy"
author: "Sam Musch - musch.sam@gmail.com"
subtitle: ''
output:
  pdf_document:
    toc: yes
    toc_depth: 4
    number_sections: yes
  #rmdformats::robobook:
    #toc: yes
    #toc_depth: '4'
    #df_print: paged
urlcolor: blue
---


```{r}
library(tidyverse)
library(lubridate)
library(Quandl)

quarters <- 16
months <- 48

```

BEA personal consumption guide: https://www.bea.gov/resources/methodologies/nipa-handbook/pdf/chapter-05.pdf


# Fred


```{r}

# Growth
real_gdp <- Quandl('FRED/A191RL1Q225SBEA', collapse = "quarterly", limit = quarters)
utilization <- Quandl('FRED/TCU', collapse = "quarterly", limit = quarters)



# ---------------------------------------

# Agriculture, forestry, fishing, and hunting
# Mining
# Utilities
# Construction
# Manufacturing
## Durable
## Non-durable
# Wholesale trade
# Retail trade
# Transportation and warehousing
# Information
# Finance, insurance, real estate, rental, and leasing
# Professional and business services
# Educational services, health care, and social assistance
# Arts, entertainment, recreation, accommodation, and food services
# Other services, except government



# ---------------------------------------

# Inflation
cpi_core <- Quandl('FRED/CPIAUCSL', collapse = "quarterly", limit = quarters)
cpi_no_food_energy <- Quandl('FRED/CPILFESL', collapse = "quarterly", limit = quarters)

## Extra inflation
# Agg Demand
# Oil



# Money supply
m2 <- Quandl('FRED/M2', collapse = "quarterly", limit = quarters)


# Fed funds rate
fed_funds_rate <- Quandl('FRED/DFF', collapse = "quarterly", limit = quarters)

# Nominal yield curve

# ---------------------------------------


# Employment
unemploy <- Quandl('FRED/UNRATE', collapse = "quarterly", limit = quarters)
## By wage maybe?
labor_fr_part <- Quandl('FRED/CIVPART', collapse = "quarterly", limit = quarters)


# Income and expenses
dpi_real <- Quandl('FRED/DSPIC96', collapse = "quarterly", limit = quarters)
dpi_nom <- Quandl('FRED/DSPI', collapse = "quarterly", limit = quarters)
# Where is disposable income going?



# Vix


# Consumer credit
con_credit <- Quandl('FED/DTCTLR_N_M', collapse = "quarterly", limit = quarters)


```







```{r}
# Goods
## Durable
### Motor vehicles
motor_vehics <- Quandl('FRED/DMOTRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'motor_vehics',
         L2 = 'Durable')

### Furniture
furniture <- Quandl('FRED/DFDHRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'furniture',
         L2 = 'Durable')

### Rec goods and vehicles
rec_goods <- Quandl('FRED/DREQRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'rec_goods',
         L2 = 'Durable')

### Others
other_dur <- Quandl('FRED/DODGRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'other_dur',
         L2 = 'Durable')


goods_durable <- bind_rows(motor_vehics, furniture, rec_goods, other_dur) %>%
  mutate(L1 = 'Services')


# ------------------------------------------------------------


## Non-durable
### Food
food <- Quandl('FRED/DFXARC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'food',
         L2 = 'NonDurable')

 

### Clothes
clothes <- Quandl('FRED/DCLORC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'clothes',
         L2 = 'NonDurable')


### Energy
energy <- Quandl('FRED/DGOERC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'energy',
         L2 = 'NonDurable')


### Other
other_non_dur <- Quandl('FRED/DONGRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'other_non_dur',
         L2 = 'NonDurable')


goods_nondurable <- bind_rows(food, clothes, energy, other_non_dur) %>%
  mutate(L1 = 'Services')


# ------------------------------------------------------------



# Services
### Housing and Utilities
house_utils <- Quandl('FRED/DHUTRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'house_utils',
         L2 = NA)

### Health care
health <- Quandl('FRED/DHLCRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'health',
         L2 = NA)


### Transport services
transport <- Quandl('FRED/DTRSRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'transport',
         L2 = NA)

### Rec services
rec_serve <- Quandl('FED/DRCARC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'rec_serve',
         L2 = NA)

### Food services
food_serve <- Quandl('FED/DFSARC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'food_serve',
         L2 = NA)


### Financial services
financial_serve <- Quandl('FED/DIFSRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'financial_serve',
         L2 = NA)

### Other
other_serve <- Quandl('FED/DOTSRC1Q027SBEA', collapse = "quarterly", limit = quarters) %>%
  mutate(L3 = 'other_serve',
         L2 = NA)


services <- bind_rows(house_utils, health, transport, rec_serve, food_serve, financial_serve, other_serve) %>%
  mutate(L1 = 'Services')

# ------------------------------------------------------------

house_spending <- bind_rows(goods_durable, goods_nondurable, services)


```











