---
title: ""
subtitle: ""
author: "Sam Musch"
urlcolor: "blue"
output:
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: true
    #df_print: knitr:kable()
---

---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=3, fig.align='left', warning=F, message=F)
kable_func <- function(data) {
  knitr::kable(data, booktabs=T, digits=2) %>%
    kable_styling(latex_options = c('striped', 'scale_down'))
}
theme_ilo <- function() {
  theme_minimal() +
    theme(
      text = element_text(family = "Bookman", color = "gray25"),
      plot.subtitle = element_text(size = 10),
      plot.caption = element_text(color = "gray30"),
      plot.background = element_rect(fill = "gray95"),
      plot.margin = unit(c(5, 10, 5, 10), units = "mm")
    )
}
mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}


```



Some Minnesota Links

```{r}
# https://geology.com/county-map/minnesota-county-map.gif

# https://i.imgur.com/nWUO9m0.png
#https://www.nytimes.com/interactive/2021/upshot/2020-election-map.html

# https://i.imgur.com/0QAkN8e.png

# Cook, Lake, St. Louis


```

```{r}
library(tidyverse)
library(usmap)
library(ggplot2)
library(bea.R)
library(fredr)
library(urbnmapr) # https://urbaninstitute.github.io/urbnmapr/articles/introducing-urbnmapr.html
fredr_set_key("07bccc6cd5cd1018027266ce854705db")
```


# Initial county data

```{r}
household_data <- left_join(countydata, counties, by = "county_fips") %>% filter(state_name %in% c('Minnesota', 'Colorado', 'South Dakota'))
household_data
```



# Census



```{r}
listCensusMetadata(
    name = "timeseries/bds", 
    type = "variables")

getCensus(
    name = "cps/fertility/jun",
    vars = *,
    year = 2020)
```




# House

Initial fred house seach

```{r}


fredr_category()
fredr_series_search_text(
  search_text = "duluth housing cbsa",
  order_by = 'title',
  limit = 1000L) %>% filter(frequency_short == 'M', units != 'Percent')


# ATNHPIUS20260Q   housing duluth
# ATNHPIUS27137A   housing st louis county
# ATNHPIUS55031A   housing douglas county
# ACTLISCOU20260   housing inventory

# NGMP20260        gdp nom
# RGMP20260        gdp real
# DULU227PCPI      per capita income

# DULU227URN       unemployment
# DULPOP           population

```




```{r}
fredr_series_search_text(
  search_text = "duluth housing cbsa",
  order_by = 'title',
  limit = 1000L) %>% filter(frequency_short == 'M', units != 'Percent')

# Quarter
house_quarter <- fredr(series_id = "ATNHPIUS20260Q")        # All-Transactions House Price Index for Duluth, MN-WI (MSA)

ggplot(house_quarter, aes(x = date, y = value)) + 
  geom_line()



# Monthly, all are only for Duluth
house_1 <- fredr(series_id = "ACTLISCOU20260") %>% mutate(type = 'listings')  # Active Listing Count
house_2 <- fredr(series_id = "AVELISPRI20260") %>% mutate(type = 'price_avg')   # Avg price
house_3 <- fredr(series_id = "MEDLISPRI20260") %>% mutate(type = 'price_med')   # Med price
house_4 <- fredr(series_id = "MEDSQUFEE20260") %>% mutate(type = 'size_med')   # Med size
house_5 <- fredr(series_id = "MEDLISPRIPERSQUFEE20260") %>% mutate(type = 'price_per_size')   # Med price / ft
house_6 <- fredr(series_id = "MEDDAYONMAR20260") %>% mutate(type = 'days')   # Med days on the market

# Counts
house_7 <- fredr(series_id = "NEWLISCOU20260") %>% mutate(type = 'listings_new') # New listings
house_8 <- fredr(series_id = "PENLISCOU20260") %>% mutate(type = 'listings_pending') # Pending listings
house_9 <- fredr(series_id = "PRIINCCOU20260") %>% mutate(type = 'listings_up') # Price up 
house_10 <- fredr(series_id = "PRIREDCOU20260") %>% mutate(type = 'listings_down') # Price down

house <- house_1 %>% 
  bind_rows(house_2) %>%
  bind_rows(house_3) %>%
  bind_rows(house_4) %>%
  bind_rows(house_5) %>%
  bind_rows(house_6) %>%
  bind_rows(house_7) %>%
  bind_rows(house_8) %>%
  bind_rows(house_9) %>%
  bind_rows(house_10)

house <- house %>% select(-series_id, -realtime_start, -realtime_end) %>% 
  mutate(date = lubridate::ymd(date),
         month = month(date),
         season = ifelse(month %in% c(12, 1, 2, 3), 'Winter', 'Winter'))

library(tbl2xts)
library(dygraphs)
library(xts)
house_ts <- tbl_xts(house, cols_to_xts = c(value), spread_by = type)
house_ts

```



```{r}
household_data %>%
  ggplot(aes(long, lat, group = group, fill = medhhincome)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Median Household Income")
```



# GDP

```{r}
fredr_series_search_text(
  search_text = "duluth gdp msa",
  order_by = 'title',
  limit = 1000L) #%>% filter(frequency_short == 'M', units != 'Percent')

gdp_1 <- fredr(series_id = "NGMP20260") %>% mutate(type = 'nominal') # Nominal
gdp_2 <- fredr(series_id = "QGMP20260") %>% mutate(type = 'quant_index') # Chain index, base = 2009
gdp_3 <- fredr(series_id = "RGMP20260") %>% mutate(type = 'real') # Real

gdp <- gdp_1 %>% 
  bind_rows(gdp_2) %>% 
  bind_rows(gdp_3) %>% 
  select(date, value, type)


ggplot(gdp %>% filter(type == 'quant_index'), aes(x = date, y = value)) +
  geom_line()

```


```{r}
fredr_series_search_text(
  search_text = "duluth industry",
  order_by = 'title',
  limit = 1000L) #%>% filter(frequency_short == 'M', units != 'Percent')
```

```{r}
minimalTheme = theme_set(theme_bw(12))
minimalTheme = theme_update(
   axis.ticks = element_blank(),
   legend.position = 'none',
   strip.background = element_blank(),
   panel.border = element_blank(),
   panel.background = element_blank(),
   panel.grid = element_blank())
```


```{r}
library(esquisse)
esquisse::esquisser(house)

ggplot(house %>% filter(type == 'listings'), aes(x = date, y = value)) +
  geom_line() +
  facet_wrap(~season, ncol = 1)

house
```



# Climate


https://www.wikiwand.com/en/Climate_of_the_United_States

Weather drivers in the US
 - Solar angle
 - Subtropical highs migration
 - Polar jet stream position

Humid continental climate





# Apartment

```{r}
fredr_series_search_text(
  search_text = "duluth",
  order_by = 'popularity',
  limit = 1000L) #%>% filter(frequency_short == 'M', units != 'Percent')
```


```{r}
fredr(series_id = "") %>% mutate(type = 'listings') 
```



# Weather

```{r}
library(weatherData)
checkDataAvailabilityForDateRange("KDLH", "2015-08-09", "2021-08-09")

```


```{r}
library('riem')
riem_networks()

riem_stations("MN_ASOS")
```



```{r}
DLH_weather <- riem_measures("DLH", date_start = "2016-01-01")
DLH_weather
```


```{r}
library(lubridate)
DLH_weather <- DLH_weather %>% 
  select(valid, tmpf) %>%
  drop_na() %>%
  mutate(valid = ymd_hms(valid))


weather <- DLH_weather %>%
  group_by(year = year(valid),
           month = month(valid),
           day = day(valid)) %>%
  summarize(tmpf = mean(tmpf))

weather <- weather %>%
  mutate(date = make_date(year, month, day))



```




```{r}
ggplot(weather, aes(x = date, y = tmpf)) +
  geom_point() #+
  #facet_grid(. ~ year)

```



